# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Stereo-DVS-AUnet
model_type: SegmentationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: stereo-dvs-train
    type: StereoImageDataset
    json_file: ./datasets/stereo_blur_data/train_v3.nori.json
    get_keys: [left_blur_img_nid, left_clean_events_nid]
    return_keys: [ lq, gt]
    random_swap_left_right: true

    gt_size: 256
    use_flip: true
    use_rot: true

    noise_std: !!float 0.01

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: stereo-dvs-test
    type: StereoImageDataset
    json_file: ./datasets/stereo_blur_data/test_v3.nori.json
    get_keys: [ left_blur_img_nid, left_clean_events_nid]
    return_keys: [ lq, gt]

# network structures
network_g:
  type: AttentionUnet

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~
#  visualization: visual/ntire2021-demo

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: BCELoss
    loss_weight: 1.
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e4
  save_img: true
  grids: true
  crop_size: 256
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
