# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Stereo-DVS-EDVR
model_type: StereoImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 3407

datasets:
  train:
    name: stereo-dvs-train
    type: StereoImageDataset
    json_file: ./datasets/stereo_blur_data/train.nori.json
    get_keys: [ left_blur_img_nid, left_sharp_img_nid, right_events_path ]
    return_keys: [ lq, gt, events ]

    gt_size: 256
    use_flip: true
    use_rot: true

    random_swap_left_right: true

    noise_std: !!float 0.01

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: stereo-dvs-test
    type: StereoImageDataset
    json_file: ./datasets/stereo_blur_data/test.nori.json
    get_keys: [ left_blur_img_nid, left_sharp_img_nid, right_events_path ]
    return_keys: [ lq, gt, events ]

# network structures
network_g:
  type: EDVR
  num_feat: 128
  num_reconstruct_block: 40

# path
path:
  pretrain_network_g: experiments/pretrained_models/EDVR_L_deblur_REDS_official-ca46bd8c.pth
  strict_load_g: false
  resume_state: ~
#  visualization: visual/ntire2021-demo

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000, 100000, 150000, 150000, 150000]
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  tsa_iter: 5000
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e4
  save_img: false
  grids: true
  crop_size: 256
  max_minibatch: 2

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
find_unused_parameters: true
dist_params:
  backend: nccl
  port: 29500
