# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# dataset size 80640
# general settings
name: N-MNIST-TransCls
model_type: TransClsModel
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 100
classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
point_num: &point_num  1024
height: &height 34
width: &width 34


# dataset and data loader settings
datasets:
  train:
    name: N-MNIST
    type: EventsClsDataset
    h5: /lzh/datasets/DVS/N-MNIST/n_mnist.h5
    labels: /lzh/datasets/DVS/N-MNIST/train.json
    sample_fn: crop
    sample_num: *point_num

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 15
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: N-MNIST
    type: EventsClsDataset
    h5: /lzh/datasets/DVS/N-MNIST/n_mnist.h5
    labels: /lzh/datasets/DVS/N-MNIST/train.json
    sample_fn: all
    sample_num: -1

# network structures
network_g:
  type: TransCls
  cls_num: 10
  point_num: *point_num
  hidden_ch: 512
  k_nearest: 16
  block_num: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: SGD
    lr: !!float 5e-2
    momentum: 0.9
    weight_decay: !!float 1e-4

  scheduler:
    type: MultiStepLR
    milestones: [100800, 134250]
    gamma: 0.1

  total_iter: 168000
  warmup_iter: -1 # no warm up

# validation settings
val:
  val_freq: !!float 2.5e4
  save_img: false
  height: *height
  width: *width
  split: true
  sample_num: *point_num
  max_minibatch: 20

  metrics:
    acc: # metric name, can be arbitrary
      type: calculate_acc

# logging settings
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 2.5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
